### ISSUE TITLE
Can not open the google drive download link for preprocessed dataset

### ISSUE THREAD

**Issue by klightz** [MinkaiXu/GeoDiff#1]
Hi, thanks for sharing this very good work!

I found the google drive link of the preprocessed dataset can not use, maybe the permission issue, could you have a double check? Thanks

**Comment by MinkaiXu** [comment]
Could you test the link now? It seems my google drive account (I use a separate account for sharing data) was somehow frozen, and just re-activated it. Ping me if there is any other issue.

**Comment by klightz** [comment]
Yeah, it works, thanks a lot
