### ISSUE TITLE
Typo in get_edge_encoder

### ISSUE THREAD

**Issue by natolambert** [MinkaiXu/GeoDiff#12]
The function found [here](https://github.com/MinkaiXu/GeoDiff/blob/c6f26dc250308bff8923a19884e601e0bb0f975a/models/encoder/edge.py#L65) uses the full variable `config` which is not passed in for the type `gaussian`. I believe it should be `cfg`, but I guess it is never used.

**Comment by MinkaiXu** [comment]
Yes, you are right, should be `cfg`.
