### ISSUE TITLE
protein conformation

### ISSUE THREAD

**Issue by orgw** [MinkaiXu/GeoDiff#13]
Hi! Thanks for the nice paper. In the paper you mentioned protein conformation is a difficult task with this model. Can you explain why linearity of proteins can be an issue? What could be some improvements?

**Comment by MinkaiXu** [comment]
Hi, thanks for your interest! I think the most important issue should be the scale of proteins, which is much larger than molecules, which requires significant effort for designing the large model. Recently I actually noticed some papers in this direction, e.g., https://arxiv.org/abs/2205.15019, which you may be interested in : )
