### ISSUE TITLE
m_{ij} notation in GNN architecture

### ISSUE THREAD

**Issue by CaptainCuong** [MinkaiXu/GeoDiff#17]
Hi Minkai Xu,

I think there is a flaw in your mathematical notation for GNN, Equation 5 and 6 in particular. I found that the notations `m_{ij}` in equation 5 and 6 are not the same.
 [m_{ij} in equation 5](https://github.com/MinkaiXu/GeoDiff/blob/main/models/epsnet/dualenc.py#L223) and [m_{ij} in equation 6](https://github.com/MinkaiXu/GeoDiff/blob/main/models/epsnet/dualenc.py#L217)

**Comment by MinkaiXu** [comment]
Here in practice we just use one layer of GFN after the graph encoders. For the final output, we only need $x$, so actually the two lines you quoted are all corresponding to Eq.5, with Eq.6 skipped since we don't need updated node embedding.
