### ISSUE TITLE
About the evaluation result

### ISSUE THREAD

**Issue by CaptainCuong** [MinkaiXu/GeoDiff#22]
Hi Minkai Xu,

I just did the experiment again for the QM9 dataset. First, I loaded checkpoint [qm9_defalut.pt](http://qm9_defalut.pt/) as directed and then generated molecules in file test_data_200. Then I evaluated the result. The configuration was unchanged. And this is the result I got which is far from what is reported in the paper. Can you help me point out where I am wrong?

|Threshold          |COV-R_mean           |COV-R_median|COV-R_std           |COV-P_mean           |COV-P_median|COV-P_std            |
|-------------------|---------------------|------------|--------------------|---------------------|------------|---------------------|
|0.05               |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.1                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.15000000000000002|0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.2                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.25               |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.3                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.35000000000000003|0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.4                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.45               |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.5                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.55               |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.6000000000000001 |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.6500000000000001 |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.7000000000000001 |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.7500000000000001 |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.8                |0.0                  |0.0         |0.0                 |0.0                  |0.0         |0.0                  |
|0.8500000000000001 |0.0008712818282196273|0.0         |0.010043636218820649|0.0001291531435072105|0.0         |0.0015309389251745573|
|0.9000000000000001 |0.0019512656531447076|0.0         |0.017972345443413227|0.0008040772011805944|0.0         |0.009349558583001788 |
|0.9500000000000001 |0.004791341358589347 |0.0         |0.035031777345238754|0.0010704722821136554|0.0         |0.012485518230590895 |
|1.0                |0.011071393787546404 |0.0         |0.06033746920615031 |0.0014361756189270965|0.0         |0.012576478788258297 |
|1.05               |0.02785163596962596  |0.0         |0.09760164876118275 |0.002088256239235334 |0.0         |0.013137146085897737 |
|1.1                |0.050183885326756585 |0.0         |0.1539042501808649  |0.002305052533617835 |0.0         |0.013453822701468766 |
|1.1500000000000001 |0.07131393162486155  |0.0         |0.2027544058067169  |0.002794815569426375 |0.0         |0.01473721653303389  |
|1.2000000000000002 |0.0896272136733261   |0.0         |0.24097809220551267 |0.0030385874376014257|0.0         |0.015380202091893936 |
|1.2500000000000002 |0.10519272679558851  |0.0         |0.26940168514127916 |0.0030919333032271537|0.0         |0.015509780895389165 |
|1.3                |0.1201200417390535   |0.0         |0.2969690219611863  |0.0031918626136827792|0.0         |0.015647150237713115 |
|1.35               |0.12968794429343244  |0.0         |0.3145997277753781  |0.0032078882547084205|0.0         |0.015645473165733947 |
|1.4000000000000001 |0.1380919632375295   |0.0         |0.329222257900698   |0.0032239138957340617|0.0         |0.015646980450294674 |
|1.4500000000000002 |0.14481928915720838  |0.0         |0.3422690799594835  |0.0032688981512446333|0.0         |0.015675449565911975 |
|1.5000000000000002 |0.1484444217192898   |0.0         |0.3489635490529071  |0.0032688981512446333|0.0         |0.015675449565911975 |
|1.55               |0.15136595224433277  |0.0         |0.35372993480729314 |0.003312357516737897 |0.0         |0.015678073912491233 |
|1.6                |0.1545163718242345   |0.0         |0.35738046349987346 |0.003312357516737897 |0.0         |0.015678073912491233 |
|1.6500000000000001 |0.15621160579402185  |0.0         |0.3597340027763653  |0.003490045326004653 |0.0         |0.01591339047111936  |
|1.7000000000000002 |0.1573636704735973   |0.0         |0.36075655834965453 |0.003609034167714933 |0.0         |0.016062095601586796 |
|1.7500000000000002 |0.15888283157561625  |0.0         |0.36202611804551377 |0.0036540184232255043|0.0         |0.01621092149213342  |
|1.8                |0.16094084923966945  |0.0         |0.36346251741369284 |0.0037053004745075556|0.0         |0.016215097753878003 |
|1.85               |0.16257208297921244  |0.0         |0.3651870925368191  |0.0037264914047893953|0.0         |0.016223739942513037 |
|1.9000000000000001 |0.16428808603667894  |0.0         |0.3664827922276133  |0.0037264914047893953|0.0         |0.016223739942513037 |
|1.9500000000000002 |0.1665315715484571   |0.0         |0.36918379077584407 |0.003753481958095738 |0.0         |0.01625688620234422  |
|2.0                |0.16802190471608855  |0.0         |0.37110519119199836 |0.003753481958095738 |0.0         |0.01625688620234422  |
|2.05               |0.16888927909002954  |0.0         |0.3722601507205121  |0.003753481958095738 |0.0         |0.01625688620234422  |
|2.1                |0.16979144016292233  |0.0         |0.3733721491607782  |0.003782954401361285 |0.0         |0.016390166013949815 |
|2.15               |0.17062136057258007  |0.0         |0.374410506390474   |0.003782954401361285 |0.0         |0.016390166013949815 |
|2.1999999999999997 |0.17115669515669515  |0.0         |0.37480276270665513 |0.003782954401361285 |0.0         |0.016390166013949815 |
|2.25               |0.17156695156695156  |0.0         |0.3750091878539932  |0.003782954401361285 |0.0         |0.016390166013949815 |
|2.3                |0.17197720797720797  |0.0         |0.37530251187845487 |0.003782954401361285 |0.0         |0.016390166013949815 |
|2.35               |0.17220425158886696  |0.0         |0.3754750166475972  |0.0037989800423869264|0.0         |0.016394097634398374 |
|2.4                |0.1725119438965593   |0.0         |0.37578435723601844 |0.0037989800423869264|0.0         |0.016394097634398374 |
|2.45               |0.17317115932500549  |0.0         |0.37653594138008967 |0.00380919559045108  |0.0         |0.01639358913277815  |
|2.5                |0.17350076703922857  |0.0         |0.3769845763598837  |0.003865137549227047 |0.0         |0.016562296643341554 |
|2.55               |0.17393293885601577  |0.0         |0.3776597780531875  |0.003865137549227047 |0.0         |0.016562296643341554 |
|2.6                |0.1744457593688363   |0.0         |0.3786305227122138  |0.003865137549227047 |0.0         |0.016562296643341554 |
|2.65               |0.17469471838702605  |0.0         |0.3790450039730917  |0.003865137549227047 |0.0         |0.016562296643341554 |
|2.7                |0.174819197896121    |0.0         |0.37926049691239844 |0.003865137549227047 |0.0         |0.016562296643341554 |
|2.75               |0.17484111330265176  |0.0         |0.37925570366239736 |0.003871072971829136 |0.0         |0.016564435920330082 |
|2.8                |0.17484111330265176  |0.0         |0.37925570366239736 |0.003871072971829136 |0.0         |0.016564435920330082 |
|2.85               |0.17486302870918255  |0.0         |0.37925115603420156 |0.003871072971829136 |0.0         |0.016564435920330082 |
|2.9                |0.17490685952224413  |0.0         |0.3792427976780918  |0.003871072971829136 |0.0         |0.016564435920330082 |
|2.95               |0.17492877492877495  |0.0         |0.3792389869664179  |0.003871072971829136 |0.0         |0.016564435920330082 |
|3.0                |0.17492877492877495  |0.0         |0.3792389869664179  |0.0038983777793537232|0.0         |0.01674437694676013  |

**Comment by MinkaiXu** [comment]
Hi,
Have you correctly used the `pretrain` branch in https://github.com/MinkaiXu/GeoDiff/tree/pretrain, as described in https://github.com/MinkaiXu/GeoDiff#generation?

**Comment by mulangonando** [comment]
Hi @MinkaiXu , thanks for your response on the Local vs Global question.
I had a challenge with the Evaluation of Properties [Task 2. Property Prediction ]. Task one Reproduces just fine.
For some reason my generated properties do not match in any way to the original.
I see in this for loop at:
https://github.com/MinkaiXu/GeoDiff/blob/c6f26dc250308bff8923a19884e601e0bb0f975a/eval_prop.py#L141-L160

We are comparing the smiles in the **dset** with the smiles in the **gens**.
In my case comparisons fell in the if statement -- line 145. In which case then I get an error.

I am not able to reproduce this task. Is there anything am missing?
My **gens** comes from the properties generated from the All_samples.pickle file obtained from the generation process.
While the **dset** is the file you gave in the Google drive folder.

Also a Question - Would the properties generated from the smiles not be different? How come you managed to get same smiles in your run? My understanding is that the generation process does not produce exactly the same conformations but rather conformations from the same distribution space?? doe this not mean then that the smiles should be different?

Hopping that you are still on these issues and would respond soon.

Thanks

**Comment by CaptainCuong** [comment]
> Hi, Have you correctly used the `pretrain` branch in https://github.com/MinkaiXu/GeoDiff/tree/pretrain, as described in https://github.com/MinkaiXu/GeoDiff#generation?

Yes, I have. Can anyone confirm for me that the evaluation result is reproducible?

**Comment by wwang2** [comment]
@CaptainCuong I started with main and got similar results as you, switching to pretrain branch fixed it. I suspect you were still using the master branch?

@MinkaiXu , maybe merge pretrain to master?
