### ISSUE TITLE
The package version is too old 

### ISSUE THREAD

**Issue by nickspark** [MinkaiXu/GeoDiff#3]
when I load data, a following error occurs, I also met this error in the running of deepdock, I think you should serialize the data to numpy/tensor/byte, and then use a new version of pygeometric to output a new dataset, or you can run your data generation code in a new pygeometric env to generate from the source data again.

RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

I think this is necessary, for a lot of newer GPUs do not support old version pyg

**Comment by MinkaiXu** [comment]
Hey Zhe,

Thanks for noting here!

Yes, the old version of PyG is a very important problem that we already noticed (https://github.com/MinkaiXu/GeoDiff#known-issues). We are trying to find time to update the PyG package dependency.
Currently, you can just use our provided environment. I think it will work well.
