### ISSUE TITLE
I got errors when training the code 

### ISSUE THREAD

**Issue by nickspark** [MinkaiXu/GeoDiff#4]
Hi, Minkai, I use your data generation code to generate datasets with a new version of pyg, however, I got the following error when training, do you have any idea?

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1479, 128]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by MinkaiXu** [comment]
Hi Zhe, By the data generation code, you refer to the ConfGF repo? (https://github.com/DeepGraphLearning/ConfGF#prepare-your-own-geom-dataset-from-scratch-optional)

**Comment by nickspark** [comment]
yes, I followed your code and generate the dataset, but still find error in training

**Comment by MinkaiXu** [comment]
umm, wired. would you mind providing the full error, like the error occurs at which line?

**Comment by nickspark** [comment]
File "train.py", line 170, in <module>
    train(it)
  File "train.py", line 104, in train
    return_unreduced_loss=True
  File "/home/***/protein/GeoDiff/models/epsnet/dualenc.py", line 244, in get_loss
    anneal_power, return_unreduced_loss, return_unreduced_edge_loss, extend_order, extend_radius, is_sidechain)
  File "/home/***/protein/GeoDiff/models/epsnet/dualenc.py", line 279, in get_loss_diffusion
    is_sidechain = is_sidechain
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/protein/GeoDiff/models/epsnet/dualenc.py", line 220, in forward
    edge_attr=edge_attr_local[local_edge_mask],
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/protein/GeoDiff/models/encoder/gin.py", line 109, in forward
    hidden = self.activation(hidden)
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/nn/functional.py", line 1299, in relu
    result = torch.relu(input)
 (function _print_stack)
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    train(it)
  File "train.py", line 107, in train
    loss.backward()
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/shared_space/***/anaconda3/envs/deepdock/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1479, 128]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by MinkaiXu** [comment]
Try modifying this part? Change from `self.edge_encoder_global` to `self.edge_encoder_local`. This is a known small issue for the current code, where the parameters are shared.

https://github.com/MinkaiXu/GeoDiff/blob/d76991dd2edfda98631f001e542ecb933d310803/models/epsnet/dualenc.py#L209-L213

**Comment by nickspark** [comment]
All these errors happen when I try with a new version of pyg and torch. I also try with an older version of packages similar to yours, it can run successfully.

after I fix the above global problem, error occurs in the following code:
        node_attr_local = self.encoder_local(
            z=atom_type,
            edge_index=edge_index[:, local_edge_mask],
            edge_attr=edge_attr_global[local_edge_mask],##global
        )
I change the global to local, then it occurs to next:
  File "/home/---/GeoDiff/models/epsnet/dualenc.py", line 250, in get_loss
    anneal_power, return_unreduced_loss, return_unreduced_edge_loss, extend_order, extend_radius, is_sidechain)
  File "/home/----/GeoDiff/models/epsnet/dualenc.py", line 285, in get_loss_diffusion
    is_sidechain = is_sidechain 

And if you are trying to move your code to a new version of pyg, I think you will also meet these? If you will try recently, I can wait for you.

**Comment by MinkaiXu** [comment]
Oh, yes. Another user recently also reported the same issue with a new PyG version. It seems this is caused by the PyG.

**Comment by MinkaiXu** [comment]
Hi,

Some other things in my mind is this part, where maybe you can change to one optimizer:

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L70-L73

you can change to something like:

```python
optimizer = get_optimizer(config.train.optimizer, nn.ModuleList([model.model_global, model.model_local]))
scheduler = get_scheduler(config.train.scheduler, optimizer)
```

And then, also change to only use one optimizer in the following training process, e.g.:

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L83-L86

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L90-L91

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L107-L108

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L116-L117

https://github.com/MinkaiXu/GeoDiff/blob/c02c9142522c6a93212a8a7b7b535f6cfbf88a7e/train.py#L175-L178

In my experiment, the single-optimizer actually can work pretty well. I'm not sure whether it is this two-optimizer scheme that causes this problem with newer package versions.

**Comment by jinzhuwei** [comment]
请问我也遇到了这个问题one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1208, 128]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead。在新的环境该如何解决

**Comment by MinkaiXu** [comment]
Hi Zhuzhu@jinzhuwei, thanks for your interest! Is it possible for you to use the provided env? Pytorch and PyG have been significantly updated recently, so I suppose moving to a new env will require many engineering details...

**Comment by jinzhuwei** [comment]
Thank you for your reply，however，when I use the environment you provided,
an error occurs: NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not
compatible with the current PyTorch installation. The current PyTorch
install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75
compute_37. If you want to use the NVIDIA GeForce RTX 3090 GPU with
PyTorch, please check the instructions at
https://pytorch.org/get-started/locally/
 warnings.warn(incompatible_device_warn.format(device_name, capability, "
".join(arch_list), device_name))。
Does this error require reinstalling CUDA?

Minkai Xu ***@***.***> 于2023年6月22日周四 12:21写道：

**Comment by MinkaiXu** [comment]
oh, I see. it seems like older cuda is required, but I know this might be too annoying...

Have you tried the things mentioned in this thread, about how to modify the code?

**Comment by jinzhuwei** [comment]
I'm very sorry, I'm a novice, I don't know much about this content yet,
except to reinstall CUDA, how can I make relevant code changes, I hope to
get your help.

Minkai Xu ***@***.***> 于2023年6月22日周四 13:51写道：

**Comment by jinzhuwei** [comment]
When I run the code in my own new environment when I do not use the
environment you provided, the following error occurs：
[image: image.png]
I searched the Internet for many ways to try to solve this problem, and I
couldn't avoid this error.

zhuzhu wei ***@***.***> 于2023年6月22日周四 13:56写道：

**Comment by jinzhuwei** [comment]
When I reinstalled CUDA, I found that the program could not run normally,
and I queried that I knew that I was using the RTX3090 graphics card, and
it seemed that I could only choose CUDA 11.0 or above, so I would like to
consult you on the running code and what the graphics card used is the
configuration. Looking forward to your response.

zhuzhu wei ***@***.***> 于2023年6月22日周四 14:11写道：
