### ISSUE TITLE
Provide data process script

### ISSUE THREAD

**Issue by Layne-Huang** [MinkaiXu/GeoDiff#5]
Could you please provide the data process script since I found that  ConfGF's code does not get the features like num_graphs, atom_type, pos, bond_index , etc.?

**Comment by MinkaiXu** [comment]
Hi Lei,

Thanks for your interest! 

Are you sure any feature is missed during running the code? The data is processed by PyG:

https://github.com/DeepGraphLearning/ConfGF/blob/38aeb6c7719343d13fa867f4b17b02ed45d09bd0/confgf/dataset/dataset.py#L264

And as you can see from the function, all the features are handled:

https://github.com/DeepGraphLearning/ConfGF/blob/38aeb6c7719343d13fa867f4b17b02ed45d09bd0/confgf/dataset/dataset.py#L28-L76

So do you have any problems when running the code?

**Comment by Layne-Huang** [comment]
> 

Thank you very much for your reply.

Is num_hs the same as num_graphs? Besides, how to get num_nodes_per_graph and batch features?

Thank you again!

**Comment by MinkaiXu** [comment]
Hi,

`num_hs seems` should be the number of Hydrogen atoms. The other mentioned features are the features of graphs. Many of them are automatically constructed from the `PyTorch_Geometric` library (https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#data-handling-of-graphs). Please take a look at their document. Thanks!

**Comment by Layne-Huang** [comment]
Thank you very much for your kind reply!
