### ISSUE TITLE
Using GeoDiff on mac

### ISSUE THREAD

**Issue by danielm322** [MinkaiXu/GeoDiff#6]
Hello, great work and thanks for sharing the code. However, when I try to install the environment on a mac, it is not compatible, it seems to work only on linux. Is there any chance you could provide an environment for mac?
Thanks!

**Comment by MinkaiXu** [comment]
Hi Daniel,

I think you can try manually installing the environment. For example:

```bash
conda create -n geodiff python=3.7.10
conda activate geodiff
conda install -c pytorch pytorch=1.8.1 torchvision torchaudio cudatoolkit=10.2
conda install -c rdkit rdkit==2020.09.1
conda install -c rusty1s -c conda-forge pytorch-geometric=1.7.2=py37_torch_1.8.0_cu102
conda install scikit-learn pandas decorator ipython networkx tqdm matplotlib
conda install -c conda-forge easydict pyyaml
```

For evaluation, the additional `psikit` package is needed:

```bash
conda install -c psi4 psi4
conda install -c conda-forge debtcollector
conda install -c iwatobipen psikit
```

I didn't try by myself but just looked through the most important packages (as well as their version) from the `env.yml`. So some packages maybe missed but you can just install by yourself from the python error import error report.

Ping me if there is any other issue :)
