### ISSUE TITLE
Question about GFN and GeoDiff-A Implementation

### ISSUE THREAD

**Issue by lyzustc** [MinkaiXu/GeoDiff#7]
Hi authors,

Thank you for sharing codes of your great work! According to your paper, GeoDiff has two different versions including GeoDiff-A and GeoDiff-C. But it seems only the codes of GeoDiff-C are provided. In addition, it is mentioned in the paper that graph field network (GFN) is used but I cannot find the codes of GFN, while SchNet seems to play the role of GFN in current implementations. 

I am wondering whether the implementations of GFN and GeoDiff-A will be provided in the future? Thanks!

Best,

**Comment by MinkaiXu** [comment]
Hi Youzhi,

Thanks a lot for your interest!!

1. I'm still preparing the code of GeoDiff-A. Actually, another most recent paper (https://arxiv.org/abs/2203.17003) takes a similar method by aligning the Center of Mass. Not sure whether they provide code but you may also take a look!
2. As elaborated in the implementation details part of the Appendix, GFN actually is just used to convert invariant features to equivariant features. You know, SchNets and GINs are just invariant neural nets, so GFN plays a role similar to the last layer of GemNet, to transform equivariant features.

Ping me if you have any problem playing with the code!

Best
Minkai

**Comment by lyzustc** [comment]
Hi Minkai,

Thanks a lot for your clarification and recommended paper! By the way, I found the authors of this paper have made their codes public [(https://github.com/ehoogeboom/e3_diffusion_for_molecules)](https://github.com/ehoogeboom/e3_diffusion_for_molecules).

Best
Youzhi
