### ISSUE TITLE
参数设置

### ISSUE THREAD

**Issue by shoujiang** [MinkaiXu/GeoDiff#9]
![image](https://user-images.githubusercontent.com/16526457/166444269-2e7a2693-eefb-4912-bf63-a2e128f344ed.png)

论文这里是1M，configs/qm9_default.yml中是max_iters: 10000000，请问您具体实验用的哪个参数

**Comment by MinkaiXu** [comment]
你好，我刚查看了一下，实验是≈3M。实际上跑实验时config我是用了10M，然后大约48h时手工停掉training进行test。我稍后更新下repo和arxiv。感谢！

**Comment by shoujiang** [comment]
非常感谢！
